export interface ScalarReferenceFixture<P> {
  readonly indicator: { readonly code: string; readonly version: number };
  readonly parameters: P;
  readonly expected: readonly (number | null)[];
  readonly tolerance: number;
  readonly firstValidIndex: number;
  readonly notes: string;
  readonly source: string;
}

export const SET_A_INPUT = {
  close: [10, 11, 12, 11, 13, 14],
  high: [11, 12, 13, 12, 14, 15],
  low: [9, 10, 11, 10, 12, 13],
  volume: [100, 120, 80, 150, 0, 200],
} as const;

const fixtureSource =
  'Hand-calculated from SET_A_INPUT; expected values are not generated by implementation code.';

export const smaFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'SMA', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 11, 34 / 3, 12, 38 / 3],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'Three-value arithmetic mean.',
  source: fixtureSource,
};

export const emaFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'EMA', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 11, 11, 12, 13],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'SMA seed at index 2; alpha = 2 / (period + 1).',
  source: fixtureSource,
};

export const wmaFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'WMA', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 34 / 3, 34 / 3, 73 / 6, 79 / 6],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'Oldest weight 1, newest weight 3.',
  source: fixtureSource,
};

export const rocFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'ROC', version: 1 },
  parameters: { period: 2 },
  expected: [null, null, 20, 0, 100 / 12, 300 / 11],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: '(current / lagged - 1) * 100.',
  source: fixtureSource,
};

export const momentumFixture: ScalarReferenceFixture<{
  readonly period: number;
}> = {
  indicator: { code: 'MOMENTUM', version: 1 },
  parameters: { period: 2 },
  expected: [null, null, 2, 0, 1, 3],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'Current close minus two-bar lagged close.',
  source: fixtureSource,
};

export const atrFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'ATR', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 2, 2, 7 / 3, 20 / 9],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'SMA seed of true range, followed by Wilder smoothing.',
  source: fixtureSource,
};

export const rsiFixture: ScalarReferenceFixture<{ readonly period: number }> = {
  indicator: { code: 'RSI', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, null, 200 / 3, 250 / 3, 2900 / 33],
  tolerance: 1e-10,
  firstValidIndex: 3,
  notes: 'Wilder average gain/loss; first change begins at index 1.',
  source: fixtureSource,
};

export const obvFixture: ScalarReferenceFixture<Record<never, never>> = {
  indicator: { code: 'OBV', version: 1 },
  parameters: {},
  expected: [0, 120, 200, 50, 50, 250],
  tolerance: 0,
  firstValidIndex: 0,
  notes: 'OBV seeds at zero; unchanged close preserves balance.',
  source: fixtureSource,
};

export const volumeSmaFixture: ScalarReferenceFixture<{
  readonly period: number;
}> = {
  indicator: { code: 'VOLUME_SMA', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 100, 350 / 3, 230 / 3, 350 / 3],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'Three-value arithmetic mean of volume.',
  source: fixtureSource,
};

export const relativeVolumeFixture: ScalarReferenceFixture<{
  readonly period: number;
}> = {
  indicator: { code: 'RELATIVE_VOLUME', version: 1 },
  parameters: { period: 3 },
  expected: [null, null, 0.8, 9 / 7, 0, 12 / 7],
  tolerance: 1e-12,
  firstValidIndex: 2,
  notes: 'Current volume divided by the inclusive three-value volume SMA.',
  source: fixtureSource,
};
